name: sleep_sounds
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^13.2.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/welcome/
    - assets/icons/
  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf

flutter_launcher_icons:
  image_path: "assets/images/app-icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#e5e5ea"
  image: assets/images/app-splash-icon.png
  color_dark: "#141927"
  image_dark: assets/images/app-splash-icon.png

  android_12:
    color: "#e5e5ea"
    image: assets/images/app-splash-icon.png
    color_dark: "#141927"
    image_dark: assets/images/app-splash-icon.png
