// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyJbMhHhtFtwXDdPoYHaejA80MAQRiABM',
    appId: '1:187128110192:android:9a0788b0b3237e6cb628b5',
    messagingSenderId: '187128110192',
    projectId: 'sleep-sounds-5f757',
    storageBucket: 'sleep-sounds-5f757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU_nKIpJBrKanGtLnzBZkwY1HUKrq9EjI',
    appId: '1:187128110192:ios:fb96fe3e29f7a1a2b628b5',
    messagingSenderId: '187128110192',
    projectId: 'sleep-sounds-5f757',
    storageBucket: 'sleep-sounds-5f757.appspot.com',
    iosClientId: '187128110192-dt3jl6pmgk82g8vqjjsdn9jkkt8rq6d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sleepSounds',
  );

}